export const refs = {
  readyBtn: document.querySelector(".ready-content"),
  startBtn: document.querySelector(".start-btn"),
  stopBtn: document.querySelector(".stop-btn"),
  watch: document.querySelector(".timer-clock"),
  readyContent: document.querySelector(".ready-btn"),
  loader: document.querySelector(".loader-wrap"),
  readyUsers: document.querySelector(".ready-users"),
  stepsList: document.querySelector(".steps-list"),
  listBtns: document.querySelector(".list-btns"),
  resetBtn: document.querySelector(".reset-btn"),
  sendBtn: document.querySelector(".send-btn"),
  resetBackdrop: document.querySelector(".reset-backdrop"),
  sendBackdrop: document.querySelector(".send-backdrop"),
  noBtn: document.querySelector(".no-btn"),
  yesBtn: document.querySelector(".yes-btn"),
  taskInput: document.querySelector(".task-input"),
  loginForm: document.querySelector(".login-form"),
  loginInput: document.querySelector(".login-input"),
  loginBtn: document.querySelector(".login-btn"),
  backBtn: document.querySelector(".back-btn"),
  logOutBtn: document.querySelector(".log-out-btn"),
  username: document.querySelector(".username"),
  taskWrap: document.querySelector(".task-wrap"),
  taskForm: document.querySelector(".task-form"),
  taskFormDescription: document.querySelector(".task-description"),
  navName: document.querySelector(".nav-name"),
};
